INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME)
VALUES ('1', 'Starwars', 'FILM', 'SF', 'Lucas','George');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME)
VALUES ('2', 'Hotel California', 'MUSIQUE', 'ROCK', 'The Eagles','');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME)
VALUES ('3', 'L''appel de Cthulhu','JEU', 'HISTORIQUE', 'Petersen','Sandy');