INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('1', 'Star Wars Episode 4 - La guerre des étoiles ', 'FILM', 'SF', 'Lucas','George', 'Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l''Empire galactique et l''Alliance rebelle. Capturée par les troupes de choc de l''Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l''Etoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s''échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au coeur des montagnes désertiques de Tatooine... ', 'https://images-na.ssl-images-amazon.com/images/I/61zAtWHeXLL._SY550_.jpg', '1977-10-19');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('2', 'Hotel California', 'MUSIQUE', 'ROCK', 'The Eagles','','Hotel California est le cinquième album studio du groupe rock américain Eagles. Le magazine rock américain Rolling Stone a classé Hotel California 37e dans sa liste des 500 plus grands albums de tous les temps. La pièce-titre, Hotel California, en est le titre le plus célèbre.','https://i.pinimg.com/originals/c6/aa/64/c6aa640236695afc1af5e85d61340476.jpg','1976-12-08');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('3', 'L''appel de Cthulhu','JEU', 'HISTORIQUE', 'Petersen','Sandy','Ce jeu emprunte à l’univers de H. P. Lovecraft son ambiance mystérieuse et oppressante. Les joueurs sont confrontés à des situations où ils doivent déjouer les complots de ces créatures et de leurs adorateurs. ','https://upload.wikimedia.org/wikipedia/en/3/33/Call_of_Cthulhu_RPG_1st_ed_1981.jpg','1981-01-01');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('4', 'Le seigneur des anneaux','LIVRE', 'FANTASY', 'Tolkien','J.R.R','Prenant place dans le monde de fiction de la Terre du Milieu, il suit la quête du hobbit Frodo Bessac, qui doit détruire l''Anneau unique afin que celui-ci ne tombe pas entre les mains de Sauron, le Seigneur des ténèbres. Plusieurs personnages lui viennent en aide, parmi lesquels son serviteur Sam, le mage Gandalf ou encore l''humain Aragorn, héritier d''une longue lignée de rois. ','https://images.fr.shopping.rakuten.com/photo/1270487382.jpg','1954-07-29');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('5', 'Star Wars Episode 1 - La menace fantôme', 'FILM', 'SF', 'Lucas','George', 'Avant de devenir un célèbre chevalier Jedi, et bien avant de se révéler l’âme la plus noire de la galaxie, Anakin Skywalker est un jeune esclave sur la planète Tatooine. La Force est déjà puissante en lui et il est un remarquable pilote de Podracer. Le maître Jedi Qui-Gon Jinn le découvre et entrevoit alors son immense potentiel. Pendant ce temps, l’armée de droïdes de l’insatiable Fédération du Commerce a envahi Naboo, une planète pacifique, dans le cadre d’un plan secret des Sith visant à accroître leur pouvoir. Pour défendre la reine de Naboo, Amidala, les chevaliers Jedi vont devoir affronter le redoutable Seigneur Sith, Dark Maul. ', 'https://www.cinemaffiche.fr/4015-tm_large_default/star-wars-la-menace-fantome-episode-1-star-wars-1-the-phantom-menace.jpg', '1999-10-13');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('6', 'Equinoxe', 'MUSIQUE', 'ELECTRO', 'Jarre','Jean-Michel','L''album est enregistré dans le studio privé de Jean-Michel Jarre sur l''équipement MCI-Studio et mixé aux Gang Recording Studio à Paris, entre janvier et août 1978. Jean-Michel Jarre déclare à propos d''Équinoxe : « J''ai voulu évoquer l''écoulement des 24 heures d''une journée, chaque partie de l''album représentant un moment différent du jour et de la nuit. Je veux que les gens se servent de mon disque pour le passer à différents moments de la journée et quand ils sont d''humeurs différentes ». Dans cet album, le musicien emploie beaucoup plus d''éléments rythmiques et dynamiques, en particulier sur l''utilisation du séquençage des basses, notamment grâce à des équipements spécialement fabriqués par son ami et collaborateur Michel Geiss. ','https://p1.storage.canalblog.com/29/39/636073/52226885.jpg','1978-11-17');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('7', 'L''appel de Cthulhu 1','JEU', 'HISTORIQUE', 'Petersen','Sandy','Ce jeu emprunte à l’univers de H. P. Lovecraft son ambiance mystérieuse et oppressante. Les joueurs sont confrontés à des situations où ils doivent déjouer les complots de ces créatures et de leurs adorateurs. ','https://upload.wikimedia.org/wikipedia/en/3/33/Call_of_Cthulhu_RPG_1st_ed_1981.jpg','1981-01-01');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('8', 'Les annales du Disque-Monde','LIVRE', 'FANTASY', 'Pratchett','Terry','Dans une dimension lointaine et passablement farfelue, un monde en forme de disque est juché sur le dos de quatre éléphants, eux-mêmes posés sur une tortue. À Ankh-Morpork, l''une des villes du Disque-Monde, les habitants croyaient avoir tout vu. Et Deuxfleurs avait l''air tellement inoffensif, avec son Bagage de bois magique circulant sur une myriade de petites jambes... Tellement inoffensif que le Praticien a chargé le calamiteux sorcier Rincevent de sa sécurité dans la cité quadrillée par la guilde des voleurs et celle des assassins. Car Deuxfleurs appartient à l''espèce la plus redoutable qui soit : c''est un touriste...','https://products-images.di-static.com/image/terry-pratchett-les-annales-du-disque-monde-tome-1-la-huitieme-couleur/9782841726899-475x500-1.jpg','1983-11-24');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('9', 'Star Wars Episode 5 - l''empire contre-attaque', 'FILM', 'SF', 'Kershner','Irvin', 'Malgré la destruction de l''Etoile Noire, l''Empire maintient son emprise sur la galaxie, et poursuit sans relâche sa lutte contre l''Alliance rebelle. Basés sur la planète glacée de Hoth, les rebelles essuient un assaut des troupes impériales. Parvenus à s''échapper, la princesse Leia, Han Solo, Chewbacca et C-3P0 se dirigent vers Bespin, la cité des nuages gouvernée par Lando Calrissian, ancien compagnon de Han. Suivant les instructions d''Obi-Wan Kenobi, Luke Skywalker se rend quant à lui vers le système de Dagobah, planète marécageuse où il doit recevoir l''enseignement du dernier maître Jedi, Yoda. Apprenant l''arrestation de ses compagnons par les stormtroopers de Dark Vador après la trahison de Lando, Luke décide d''interrompre son entraînement pour porter secours à ses amis et affronter le sombre seigneur Sith... ', 'https://www.mauvais-genres.com/21587/star-wars-l-empire-contre-attaque-affiche-de-film-style-a-40x60-cm-r1990-harrison-ford-george-lucas.jpg', '1980-08-20');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('10', 'Oxygène', 'MUSIQUE', 'ELECTRO', 'Jarre','Jean-Michel','Vendu à environ 18 millions d''exemplaires dans le monde2, il s''agit d''un des plus gros succès de l''histoire de la discographie française. En France, les ventes certifiées de l''album s''élèvent à 1 739 100 exemplaires3. Oxygène reste un des albums de musique électronique les plus vendus de tous les temps. Jean Michel Jarre a eu beaucoup de difficultés à sortir cet album, celui-ci étant totalement instrumental et dépourvu de titre conçu comme single. Cependant, le succès a été au rendez-vous. La piste Oxygène Part IV sort en 45 tours et devient l''un des thèmes électroniques les plus célèbres de l''histoire. Cet album mélodique et aérien se rapproche des sonorités de certaines œuvres de Tangerine Dream ou Vangelis et contraste avec d''autres productions de musique électronique de l''époque, comme le son industriel de Kraftwerk ou celui plus « cosmique » de Klaus Schulze (notamment sur l''album Timewind sorti en 1975), ouvrant ainsi la musique électronique au grand public.  ','https://media.senscritique.com/media/000004813697/source_big/Oxygene.jpg','1976-12-02');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('11', 'L''appel de Cthulhu 2','JEU', 'HISTORIQUE', 'Petersen','Sandy','Ce jeu emprunte à l’univers de H. P. Lovecraft son ambiance mystérieuse et oppressante. Les joueurs sont confrontés à des situations où ils doivent déjouer les complots de ces créatures et de leurs adorateurs. ','https://upload.wikimedia.org/wikipedia/en/3/33/Call_of_Cthulhu_RPG_1st_ed_1981.jpg','1981-01-01');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('12', 'Harry Potter à l''école des sorciers','LIVRE', 'ENFANT', 'Rowling','J.K.','Le jour de ses onze ans, Harry Potter, un orphelin élevé par un oncle et une tante qui le détestent, voit son existence bouleversée. Un géant vient le chercher pour l''emmener à Poudlard, une école de sorcellerie ! Voler en balai, jeter des sorts, combattre les trolls : Harry se révèle un sorcier doué. Mais un mystère entoure sa naissance et l''effroyable V., le mage dont personne n''ose prononcer le nom. ','https://kbimages1-a.akamaihd.net/f37dc46e-c4cb-457a-865d-92a2b0e0f85d/1200/1200/False/harry-potter-a-l-ecole-des-sorciers-1.jpg','1997-06-26');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('13', 'Star Wars Episode 6 - Le retour du Jedi', 'FILM', 'SF', 'Marquand','Richard', 'L''Empire galactique est plus puissant que jamais : la construction de la nouvelle arme, l''Etoile de la Mort, menace l''univers tout entier... Arrêté après la trahison de Lando Calrissian, Han Solo est remis à l''ignoble contrebandier Jabba Le Hutt par le chasseur de primes Boba Fett. Après l''échec d''une première tentative d''évasion menée par la princesse Leia, également arrêtée par Jabba, Luke Skywalker et Lando parviennent à libérer leurs amis. Han, Leia, Chewbacca, C-3PO et Luke, devenu un Jedi, s''envolent dès lors pour une mission d''extrême importance sur la lune forestière d''Endor, afin de détruire le générateur du bouclier de l''Etoile de la Mort et permettre une attaque des pilotes de l''Alliance rebelle. Conscient d''être un danger pour ses compagnons, Luke préfère se rendre aux mains de Dark Vador, son père et ancien Jedi passé du côté obscur de la Force. ', 'https://images-na.ssl-images-amazon.com/images/I/A1S46tSt22L._SY879_.jpg', '1983-10-19');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('14', 'Les chants magnétiques', 'MUSIQUE', 'ELECTRO', 'Jarre','Jean-Michel','Après Oxygène et Équinoxe - dédiés à la nature, Jean-Michel Jarre choisit comme thème principal l''action des Hommes sur leur milieu. L''album contient ainsi des bruits de trains, de rouages, des bruits métalliques et mécaniques. L''album est enregistré dans le studio personnel de l''artiste à Croissy-sur-Seine dans les Yvelines. Cet album est l''un des premiers à utiliser massivement la technique de l''échantillonnage. Jean-Michel Jarre a été particulièrement inspiré par Andy Warhol et par une fascination pour la reproductibilité des sons digitaux. Il est l''un des premiers artistes à utiliser l''échantillonneur Fairlight CMI.','https://images-na.ssl-images-amazon.com/images/I/71ED8Ao3lHL._SL1500_.jpg','1981-05-12');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('15', 'L''appel de Cthulhu 3','JEU', 'HISTORIQUE', 'Petersen','Sandy','Ce jeu emprunte à l’univers de H. P. Lovecraft son ambiance mystérieuse et oppressante. Les joueurs sont confrontés à des situations où ils doivent déjouer les complots de ces créatures et de leurs adorateurs. ','https://upload.wikimedia.org/wikipedia/en/3/33/Call_of_Cthulhu_RPG_1st_ed_1981.jpg','1981-01-01');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('16', 'Dune','LIVRE', 'SF', 'Herbert','Franck','Il n''y a pas, dans tout l''Empire, de planète plus inhospitalière que Dune. Partout des sables à perte de vue. Une seule richesse : l''épice de longue vie, née du désert, et que tout l''univers achète à n''importe quel prix. Richesse très convoitée : quand Leto Atréides reçoit Dune en fief, il flaire le piège. Il aura besoin des guerriers Fremen qui, réfugiés au fond du désert, se sont adaptés à une vie très dure en préservant leur liberté, leurs coutumes et leur foi mystique. Ils rêvent du prophète qui proclamera la guerre sainte et qui, à la tête des commandos de la mort, changera le cours de l''histoire. Cependant les Révérendes Mères du Bene Gesserit poursuivent leur programme millénaire de sélection génétique ; elles veulent créer un homme qui concrétisera tous les dons latents de l''espèce. Le Messie des Fremen est-il déjà né dans l''Empire ? ','https://media.senscritique.com/media/000006531862/source_big/Dune_Le_Cycle_de_Dune_tome_1.jpg','1965-08-01');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('17', 'Rogue One', 'FILM', 'SF', 'Edwards','Gareth', 'Situé entre les épisodes III et IV de la saga Star Wars, le film nous entraîne aux côtés d’individus ordinaires qui, pour rester fidèles à leurs valeurs, vont tenter l’impossible au péril de leur vie. Ils n’avaient pas prévu de devenir des héros, mais dans une époque de plus en plus sombre, ils vont devoir dérober les plans de l’Étoile de la Mort, l’arme de destruction ultime de l’Empire.', 'https://images-na.ssl-images-amazon.com/images/I/719nQvM2%2BwL._AC_SY679_.jpg', '2016-12-14');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('18', 'Hotel California 4', 'MUSIQUE', 'ROCK', 'The Eagles','','Hotel California est le cinquième album studio du groupe rock américain Eagles','http://images.45cat.com/eagles-usa-hotel-california-asylum-3-s.jpg','1976-12-08');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('19', 'L''appel de Cthulhu 4','JEU', 'HISTORIQUE', 'Petersen','Sandy','Ce jeu emprunte à l’univers de H. P. Lovecraft son ambiance mystérieuse et oppressante. Les joueurs sont confrontés à des situations où ils doivent déjouer les complots de ces créatures et de leurs adorateurs. ','https://upload.wikimedia.org/wikipedia/en/3/33/Call_of_Cthulhu_RPG_1st_ed_1981.jpg','1981-01-01');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('20', 'Les neuf princes d''Ambre','LIVRE', 'FANTASY', 'Zelazny','Roger','Ambre est un royaume médiéval ; comme tous les autres il possède une capitale, un palais, une cour, une famille royale et des intrigues. Mais Ambre est aussi bien plus : lieu mythique considéré comme le centre de l''univers. Seul lieu réel, tous les autres n''en sont qu''un reflet, dans l''ombre, comme la Terre. Considérée comme très intéressante par la plupart des princes d''Ambre, elle leur sert de résidence secondaire, voire de cachette. Car la vie d''un prince ou d''une princesse n''est pas de tout repos. Seuls dépositaires du pouvoir quasi divin de se déplacer entre les mondes, ils n''en restent pas moins humains : au mieux rivaux, ils sont le plus souvent ennemis jurés. En effet, depuis la disparition mystérieuse d''Obéron, le père de cette grande famille, le trône est vacant et la succession des plus agitée.','https://images-na.ssl-images-amazon.com/images/I/4164Zob5KgL.jpg','1970-06-01');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('21', 'La reine des neiges', 'FILM', 'ENFANT', 'Buck','Chris', 'Anna, une jeune fille aussi audacieuse qu’optimiste, se lance dans un incroyable voyage en compagnie de Kristoff, un montagnard expérimenté, et de son fidèle renne, Sven à la recherche de sa sœur, Elsa, la Reine des Neiges qui a plongé le royaume d’Arendelle dans un hiver éternel…  En chemin, ils vont rencontrer de mystérieux trolls et un drôle de bonhomme de neige nommé Olaf, braver les conditions extrêmes des sommets escarpés et glacés, et affronter la magie qui les guette à chaque pas. ', 'http://img.over-blog-kiwi.com/0/55/25/40/20140226/ob_c43127_1011006-fr-la-reine-des-neiges-138366440.jpg', '2013-12-04');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('22', 'Hotel California 5', 'MUSIQUE', 'ROCK', 'The Eagles','','Hotel California est le cinquième album studio du groupe rock américain Eagles','http://images.45cat.com/eagles-usa-hotel-california-asylum-3-s.jpg','1976-12-08');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('23', 'L''appel de Cthulhu 5','JEU', 'HISTORIQUE', 'Petersen','Sandy','Ce jeu emprunte à l’univers de H. P. Lovecraft son ambiance mystérieuse et oppressante. Les joueurs sont confrontés à des situations où ils doivent déjouer les complots de ces créatures et de leurs adorateurs. ','https://upload.wikimedia.org/wikipedia/en/3/33/Call_of_Cthulhu_RPG_1st_ed_1981.jpg','1981-01-01');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('24', 'Le journal d''un chat assassin','LIVRE', 'ENFANT', 'Fine','Anne','Un chat qui ne mâche pas ses mots, ça n''existe pas  ! Pourtant, le héros de ce livre est bel et bien un chat. Il s''appelle Tuffy. Dans son journal de bord, il raconte la difficulté qu''il a d''être confronté à la plus totale incompréhension de ses maîtres. Surtout lorsqu''il ramène à la maison des animaux morts. Tuffy essaie bien de s''en empêcher... Mais aller contre nature relève d''un exploit qui n''est pas à la portée de n''importe quel chat, même de bonne volonté. Un beau jour, Tuffy est accusé du meurtre de Thumper, le lapin des voisins. Les mésaventures commencent pour Tuffy, mais pas pour ses lecteurs, qui auront, eux, le plaisir de rire à chacune des pages de ce petit roman plein de rythme et d''humour. ','https://products-images.di-static.com/image/anne-fine-le-chat-assassin-journal-d-un-chat-assassin/9782211042871-475x500-1.jpg','1997-08-28');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('25', 'Monsieur le Prof','LIVRE', 'COMEDIE', 'Chamiot-Poncet','Enora','Monsieur Le Prof est un personnage. Prof d''anglais, il souffre quotidiennement quand il tente d''apprendre à ses élèves le présent progressif, mais aussi quand il faut affronter les parents d''élèves, certains collègues en salle des professeurs ou lors des fameux conseils de classe. Sans oublier les repas à la cantine, la visite inopinée d''un inspecteur d''académie ou encore la toujours pénible photo de classe. Astuces de profs, extraits de copies d''élèves, de bulletins scolaires ou de mots d''excuse, listes improbables… Il y a dans cet agenda tout ce qu''on n''a jamais vu réuni dans un livre autour de l''enseignement. Chaque page du livre, apportera un éclairage décalé et amusant sur le quotidien des enseignants, et donc des élèves. Le livre parfait pour aborder avec humour et dérision la rentrée scolaire ! ','https://images-na.ssl-images-amazon.com/images/I/51j%2BY3wIxOL._SX307_BO1,204,203,200_.jpg','2018-08-22');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('26', 'Le roi lion','FILM', 'ENFANT', 'Allers','Roger','Sur les Hautes terres d’Afrique règne un lion tout-puissant, le roi Mufasa, respecté pour sa sagesse et sa générosité. Son jeune fils Simba sait qu’un jour il lui succèdera, conformément aux lois universelles du cycle de la vie. Cependant, l’univers de Simba n’est pas aussi sûr qu’il le croit. Scar, le frère de Mufasa, intrigue pour l’éliminer en même temps que son successeur. Il Misant sur la curiosité enfantine et le tempérament aventureux de Simba, Scar l''incite à se rendre dans un mystérieux et dangereux cimetière d’éléphants. Mufasa arrive à temps pour sauver son fils. Mais Scar ne renonce pas à ses projets. Il attire Simba dans un ravin et lance à sa poursuite un troupeau de gnous. Mufasa sauve à nouveau son fils, mais il meurt, poussé d''une falaise par son frère félon. Scar blâme Simba pour la mort du Roi et le persuade de quitter pour toujours les Hautes terres. Simba est seul et démuni. C’est alors que le destin place sur sa route un curieux tandem d’amis...','https://images.epagine.fr/734/9782017099734_1_75.jpg','1994-11-23');

INSERT INTO MEDIA (ID, LABEL, CATEGORY, TYPE, AUTHOR_NAME, AUTHOR_SURNAME, DESCRIPTION, MEDIA_IMAGE_URL, PUBLICATION_DATE)
VALUES ('27', 'Le prénom','FILM', 'COMEDIE', 'De La Patellière','Alexandre','Vincent, la quarantaine triomphante, va être père pour la première fois. Invité à dîner chez Élisabeth et Pierre, sa sœur et son beau-frère, il y retrouve Claude, un ami d’enfance. En attendant l’arrivée d’Anna, sa jeune épouse éternellement en retard, on le presse de questions sur sa future paternité dans la bonne humeur générale... Mais quand on demande à Vincent s’il a déjà choisi un prénom pour l’enfant à naître, sa réponse plonge la famille dans le chaos','https://media3.woopic.com/api/v1/images/174%2Fcinemovies%2Fca9%2F1ea%2F3965dd156ba5752756fd125336%2Fmovies-188448-3.jpg?format=822x700&quality=85','2012-04-25');

INSERT INTO USER (ID, LOGIN, PASSWORD, USER_NAME, USER_SURNAME, AVATAR_IMAGE_URL, EMAIL, ACTIVE)
VALUES ('99991','Bilbo123','','John','Doe', 'https://greendestinations.org/wp-content/uploads/2019/05/avatar-exemple-300x277.jpg','john.doe@gmail.com','TRUE');

INSERT INTO USER (ID, LOGIN, PASSWORD,USER_NAME, USER_SURNAME, AVATAR_IMAGE_URL, EMAIL,ACTIVE)
VALUES ('99992','Bebe Yoda','','Anne','Honime', 'https://s1.thcdn.com//productimg/1600/1600/12376863-2094725918660345.jpg','a.honime@gmail.com','TRUE');

INSERT INTO USER (ID, LOGIN, PASSWORD,USER_NAME, USER_SURNAME, AVATAR_IMAGE_URL, EMAIL,ACTIVE)
VALUES ('99993','moi','','password','', 'https://s1.thcdn.com//productimg/1600/1600/12376863-2094725918660345.jpg','a.honime@gmail.com','TRUE');

INSERT INTO USER (ID, LOGIN, PASSWORD, USER_NAME, USER_SURNAME, AVATAR_IMAGE_URL, EMAIL, ACTIVE)
VALUES ('99994','UserTest1A','','Alpha','Beta', 'https://greendestinations.org/wp-content/uploads/2019/05/avatar-exemple-300x277.jpg','john.doe@gmail.com','TRUE');

INSERT INTO USER (ID, LOGIN, PASSWORD,USER_NAME, USER_SURNAME, AVATAR_IMAGE_URL, EMAIL,ACTIVE)
VALUES ('99995','UserTest2A','','Gamma','Delta', 'https://s1.thcdn.com//productimg/1600/1600/12376863-2094725918660345.jpg','a.honime@gmail.com','TRUE');

INSERT INTO USER (ID, LOGIN, PASSWORD,USER_NAME, USER_SURNAME, AVATAR_IMAGE_URL, EMAIL,ACTIVE)
VALUES ('99996','UserTest3I','password','Epsilon','Sigma', 'https://s1.thcdn.com//productimg/1600/1600/12376863-2094725918660345.jpg','a.honime@gmail.com','FALSE');

INSERT INTO MEDIA_NOTATION (NOTATION_ID, LIKED, MEDIAJPA_ID, USERJPA_ID)
VALUES (9991, 'TRUE', '1', '99991');

INSERT INTO MEDIA_NOTATION (NOTATION_ID, LIKED, MEDIAJPA_ID, USERJPA_ID)
VALUES (9992, 'FALSE', '2', '99991');

INSERT INTO MEDIA_NOTATION (NOTATION_ID, LIKED, MEDIAJPA_ID, USERJPA_ID)
VALUES (9993, 'FALSE', '1', '99992');

INSERT INTO REVIEW(ID, COMMENT, REVIEW_DATE, MEDIAJPA_ID, USERJPA_ID)
VALUES ('99991','Ah, ce film! Immortel, magnifique, novateur! George Lucas et toute la clique se sont vraiment surpassés, tant sur les décors, les idées et l''originalité! Je pense que c''est un peu la base de la SF au ciné; ce film a instauré nombres de choses: l''hyperdrive, les blasters, les sabres-laser, les vaisseaux spatiaux et les Destroyers,... Bien que le film date de 77, c''est comme s''il n''avait pas pris une ride! La bande-son concoctée par notre bien aimé John Williams, les effets spéciaux, bien que certains soient, très légèrement, dépassés et les "méchants" ( Darth Vader et Darth Sidious) le préservent de la vieillesse. Je regrette de n''être que de la génération de 90 et de n''avoir pu découvrir la Première Trilogie SW au ciné. Le scénario, bien qu''extrêmement simple, est, paradoxalement, très original. Les races d''aliens sont aussi nombreuses que variées; les vaisseaux ( Tie, X-wing,...) sont de très bonne conception; les "méchants" sont tous entrés dans l''histoire du cinéma comme étant des icones de la brutalité. En résumé, un film à voir au moins une fois dans sa vie si l''on se veut être un réel cinéphile. ','2019-12-12','1','99991');

INSERT INTO REVIEW(ID, COMMENT, REVIEW_DATE, MEDIAJPA_ID, USERJPA_ID)
VALUES ('99992','l''auteur cède à la facilité','2019-12-13','1','99992');

INSERT INTO REVIEW(ID, COMMENT, REVIEW_DATE, MEDIAJPA_ID, USERJPA_ID)
VALUES ('99993','Nul! j''adore!','2019-12-14','2','99992');